UniversityApp/Models/Courses/Course.cs
using System.ComponentModel.DataAnnotations;
using UniversityApp.Models.Employees;
using UniversityApp.Models.Sessions;
using UniversityApp.Models.Students;

namespace UniversityApp.Models.Courses;

public class Course
{
    [Key] public int Id { get; init; }

    [Required(ErrorMessage = "Course Title is required!")]
    [StringLength(30, MinimumLength = 2, ErrorMessage = $"{nameof(Title)} must be between 2 to 30 characters.")]
    public string Title { get; init; } = null!;

    public Dictionary<WeekDays, List<Session>>? WeeklyLessonsPerDay { get; init; } = [];

    [Range(0, 100, ErrorMessage = $"{nameof(OralMark)} must be between 0 and 100.")]
    public int OralMark { get; set; }

    [Range(0, 100, ErrorMessage = $"{nameof(WritingMark)} must be between 0 and 100.")]
    public int WritingMark { get; set; }

    public Teacher Teacher { get; set; } = null!;
    public List<Student> Students { get; set; } = [];
}

UniversityApp/Models/Employees/BoardingMember.cs
using UniversityApp.Models.Students;

namespace UniversityApp.Models.Employees;

internal class BoardingMember : Employee
{
    public override int Id { get; init; }
    public override string FirstName { get; set; } = null!;
    public override string LastName { get; set; } = null!;
    public override int Age { get; set; }
    public override double Wage { get; set; }
    public override DateTime StartDate { get; set; }

    public List<Student> Students { get; set; } = [];
    public List<Teacher> Teachers { get; set; } = [];
}

UniversityApp/Models/Employees/Cleaner.cs
using UniversityApp.Models.Sessions;

namespace UniversityApp.Models.Employees;

internal class Cleaner : Employee
{
    public override int Id { get; init; }
    public override string FirstName { get; set; } = null!;
    public override string LastName { get; set; } = null!;
    public override int Age { get; set; }
    public override double Wage { get; set; }
    public override DateTime StartDate { get; set; }

    public Dictionary<WeekDays, List<Session>>? WeeklyTasksPerDay { get; set; } = [];
}

UniversityApp/Models/Employees/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace UniversityApp.Models.Employees;

public abstract class Employee
{
    [Key] public abstract int Id { get; init; }

    [Required]
    [StringLength(20, ErrorMessage = $"{nameof(FirstName)} maximum length is 20")]
    public abstract string FirstName { get; set; }

    [Required]
    [StringLength(20, ErrorMessage = $"{nameof(LastName)} maximum length is 20")]
    public abstract string LastName { get; set; }

    public abstract int Age { get; set; }

    public abstract double Wage { get; set; }

    [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}"/*, ApplyFormatInEditMode = true*/)]
    public abstract DateTime StartDate { get; set; }
}

UniversityApp/Models/Employees/Teacher.cs
using System.ComponentModel.DataAnnotations;
using UniversityApp.Models.Courses;

namespace UniversityApp.Models.Employees;

public class Teacher : Employee
{
    public override int Id { get; init; }
    public override string FirstName { get; set; } = null!;
    public override string LastName { get; set; } = null!;
    public override int Age { get; set; }
    public override double Wage { get; set; }
    public override DateTime StartDate { get; set; }

    [Required(ErrorMessage = "Teacher cannot serve without having courses!")]
    public List<Course> Courses { get; set; } = [];
}

UniversityApp/Models/ErrorViewModel.cs
namespace UniversityApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

UniversityApp/Models/Students/Student.cs
using System.ComponentModel.DataAnnotations;
using UniversityApp.Models.Courses;

namespace UniversityApp.Models.Students;

public class Student
{
    [Key] public int Id { get; init; }
    public DateTime StartDate { get; init; }
    public List<Course> Courses { get; set; } = [];
}

UniversityApp/Controllers/AdminStudentsController.cs
using Microsoft.AspNetCore.Mvc;

namespace UniversityApp.Controllers
{
    public class AdminStudentsController : Controller
    {
        [HttpGet]
        public IActionResult Students()
        {
            return View();
        }
    }
}

UniversityApp/Controllers/AdminTeachersController.cs
using Microsoft.AspNetCore.Mvc;
using UniversityApp.Data;
using UniversityApp.DTOs.TeacherDTOs;
using UniversityApp.Services.AdminServices;

namespace UniversityApp.Controllers;

public class AdminTeachersController : Controller
{
    /* Service Injection Fail */
    // private readonly IAdminTeachersService _adminTeachersService;
    // internal AdminTeachersController(IAdminTeachersService adminTeachersService)
    // {
    //     _adminTeachersService = adminTeachersService;
    // }

    /* Plan-B, DB-list & service as coupled dependencies in Controller */
    private static readonly TeachersMockData TeacherMocks = new();
    private readonly AdminTeachersService _adminTeachersService = new(TeacherMocks);

    [HttpGet]
    public IActionResult Teachers() =>
        View(_adminTeachersService.GetTeachers());

    [HttpGet]
    public IActionResult Create() =>
        View();

    [HttpPost]
    public IActionResult Create(CreateTeacherDto dto)
    {
        _adminTeachersService.CreateTeacher(dto);
        return RedirectToAction("Teachers");
    }

    [HttpGet]
    public IActionResult Edit(int id) =>
        View(_adminTeachersService.UpdateTeacher(id));

    [HttpPost]
    public IActionResult Edit(UpdateTeacherDto dto)
    {
        _adminTeachersService.UpdateTeacher(dto);
        return RedirectToAction("Teachers");
    }
    
    [HttpPost]
    public IActionResult Delete(int id) 
    {
        _adminTeachersService.RemoveTeacherById(id);
        return RedirectToAction("Teachers");
    }
    
}

UniversityApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UniversityApp.Models;

namespace UniversityApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UniversityApp/Views/AdminStudents/Students.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h3>students list</h3>
<ul>
    <li><p>student 1</p></li>
    <li><p>student 2</p></li>
    <li><p>student 3</p></li>
</ul>

UniversityApp/Views/AdminTeachers/Teachers.cshtml
@model List<UniversityApp.DTOs.TeacherDTOs.GetAllTeachersDto>?
@{
    ViewData["Title"] = "Teachers";
}

<h3>teachers list</h3>
@if (Model != null)
{
    <ul>
        @foreach (var i in Model)
        {
        <li>
            <p>@i.FirstName</p>
            <p>@i.LastName</p>
            <p>@i.Age</p>
        </li>
        }
    </ul>
}
else
{
    <p>No Teachers registered.</p>
}

UniversityApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UniversityApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversityApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UniversityApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminTeachers" asp-action="Teachers">Teachers</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminStudents" asp-action="Students">Students</a></li>
                            </ul>
                        </li>
                        @*
                        <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - UniversityApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>